POST http://www.m-glory.net/qnh-goods-bsp/bsp/itemRegion/findItemRegionList
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlY29kZSI6WyI5RUIwQTdFRUEwOUEzNzA1QkI0RDIzQjIwRUQ3Q0NDRiJdLCJlbnRfaWQiOiIxNzE3MDExMDEwNDM5MTQwNDAwIiwiY29kZSI6ImxzY3MiLCJuYW1lIjoi5Lmd5rGf6IGU55ubLea1i-ivlSIsInVzZXJ0eXBlIjoiMiIsImlzX2JpbmRpbmciOnRydWUsInN0YXR1cyI6IjEiLCJtb2JpbGVObyI6IjEzMzMwMDM0MDc3IiwidXNlcnN0b3JlcyI6W10sImNoYW5uZWxfa2V5d29yZHMiOlsiWUpHIl0sImFkbWluX3dlYl92ZXJzaW9uIjoiMi41IiwicW5oX21lcmNoYW50X2NlbnRlciI6IjEiLCJwY19yZWNlaXB0IjoiMSIsInBpY2tpbmciOiIxIiwicmlkZXJfYXBwbGV0IjoiMSIsInN0b3JlX2FwcGxldCI6IjEiLCJhbmRyb2lkX3JlY2VpcHQiOiIxIiwic3lzdGVtIjoiYnNwMi1uZyIsImlzcyI6InRlY2hmdXNlciIsImV4cCI6MTU5MDQ4MzYzOCwic3ViIjoiYnNwIiwiYXVkIjoiYnNwIn0._IBUYpcxXyPMy6yC8X6cirsZosj5W5wZ5aPbGwYwNbk
Content-Type: application/json;charset=UTF-8

{"page_no":1,"page_size":20,"sortDirKey":"DESC","sort":"timestamp","search":{"item_code":"","barcode":"","region_code":"0108","item_name":"","status":"","sale_status":"","receive_stock":"","receive_price":"","un_channel_keyword":false,"un_online_channel":false,"start_money":"","end_money":"","img":false,"manual_onoffline":false,"status_time":false,"sell_out_online":false,"erp_status":""},"count":0,"rowno":0}